eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    status-page-url: http://localhost:${server.port}/info
    health-check-url: http://localhost:${server.port}/healthCheck
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka