server:
  port: 8080

spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  sql:
    init:
      mode: always #초기 구동시 스크립트 실행
  datasource:
    initialization-mode: always
    hikari:
      data-source-properties:
        oracle:
          jdbc:
            timezoneAsRegion: false
  jpa:
    hibernate:
      ddl-auto: update # 테이블 생성 또는 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

greeting:
  message: Welcome to the sample User Service

logging:
  level:
    org.springframework.security: DEBUG  # Spring Security만 디버그 활성화
    org.springframework: INFO           # 나머지 Spring 관련 로깅은 INFO로 설정
    com.example.userservice: DEBUG

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
