global:
  scrape_interval: 10s  # 메트릭 수집 주기 (기본값: 15초)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus 자체 메트릭 수집

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308'] # Kafka Exporter를 Prometheus에서 모니터링

  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:8083'] # Kafka Connect API 모니터링

  - job_name: 'user-service'
    metrics_path: '/user-service/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8000' ]

  - job_name: 'order-service'
    metrics_path: '/order-service/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8000' ]

  - job_name: 'catalog-service'
    metrics_path: '/catalog-service/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8000' ]
