version: "2"
networks:
  kafka_default:
    external: true
services:
  zookeeper:
    networks:
      - kafka_default
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    networks:
      - kafka_default
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-connect:
    networks:
      - kafka_default
    restart: always
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka-connect
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'localhost:9092'
      CONNECT_RETRY_BACKOFF_MS: "5000"
      CONNECT_REQUEST_TIMEOUT_MS: "20000"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
    volumes:
      - ./jars:/etc/kafka-connect/jars
    ports:
      - "8083:8083"

  kafka-init:
    image: wurstmeister/kafka
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      kafka-topics.sh --create --topic user-events --bootstrap-server kafka:9092 --partitions 3 --replication-factor 2 --replica-assignment 0:1,1:2,2:0;
      kafka-topics.sh --create --topic transaction-events --bootstrap-server kafka:9092 --partitions 3 --replication-factor 2 --replica-assignment 0:1,1:2,2:0;
      kafka-topics.sh --create --topic logs-events --bootstrap-server kafka:9092 --partitions 2 --replication-factor 2 --replica-assignment 0:1,1:2;
      "

volumes:
  kafka_data: