server:
  port: 8761

spring:
  application:
    name: discoveryserivce
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false